<?php

namespace WorkBundle\Repository;

/**
 * CommandesClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesClientRepository extends \Doctrine\ORM\EntityRepository
{
}
