<?php

namespace WorkBundle\Repository;

/**
 * CommandesPharmacieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesPharmacieRepository extends \Doctrine\ORM\EntityRepository
{
}
