<?php

namespace WorkBundle\Repository;

/**
 * FournisseursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournisseursRepository extends \Doctrine\ORM\EntityRepository
{
}
