<?php

namespace WorkBundle\Repository;

/**
 * MedicamentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicamentsRepository extends \Doctrine\ORM\EntityRepository
{
}
