work_fournisseurs:
    resource: "@WorkBundle/Controller/FournisseursController.php"
    type:     annotation

work_medicaments:
    resource: "@WorkBundle/Controller/MedicamentsController.php"
    type:     annotation

user_user:
    resource: "@UserBundle/Controller/UserController.php"
    type:     annotation

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

work:
    resource: "@WorkBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"    
